run install-k as root

diff --git a/install-k b/install-k
--- a/install-k
+++ b/install-k
@@ -1,5 +1,9 @@
 #!/bin/sh -e
 
+if [ `id -u` -ne 0 ]; then
+  echo "$0: error: This script must be run as root."
+  exit 1
+fi
 TAG=`git describe HEAD --tags`
 . /etc/os-release
 case $ID in
@@ -33,8 +37,8 @@ case $ID in
 		;;
 esac
 
-sudo apt-get update
-sudo apt-get install -y curl
+apt-get update
+apt-get install -y curl
 curl -L https://github.com/kframework/k/releases/download/$TAG/kframework_5.0.0_amd64_$CODENAME.deb -o kframework_5.0.0_amd64.deb
-sudo apt-get install -y ./kframework_5.0.0_amd64.deb
+apt-get install -y ./kframework_5.0.0_amd64.deb
 rm -f kframework_5.0.0_amd64.deb
