Setting `--directory` flag option as `[DEPRECATED]` on bash scripts Outputting a `WARNING` when using `--directory` on bash scripts

diff --git a/k-distribution/src/main/scripts/bin/kparse b/k-distribution/src/main/scripts/bin/kparse
--- a/k-distribution/src/main/scripts/bin/kparse
+++ b/k-distribution/src/main/scripts/bin/kparse
@@ -46,7 +46,7 @@ $(k_util_usage)
 
 $KPARSE options:
 
-  -d, --directory DIR      Look for a kompiled directory ending in "-kompiled"
+  -d, --directory DIR      [DEPRECATED] Look for a kompiled directory ending in "-kompiled"
                            under the directory DIR
   -h, --help               Display this help and exit
       --definition DIR     Exact path to the kompiled directory.
@@ -74,6 +74,7 @@ do
   else
     case "$arg" in
       -d|--directory)
+      echo "[Warning]: -d/--directory is deprecated. Use --definition instead." >&2
       dir="$2"
       shift
       ;;
@@ -171,7 +172,7 @@ else
 fi
 
 if ! $hasKompiledDir; then
-  error 1 'Could not find a compiled definition. Use --directory or --definition to specify one.'
+  error 1 'Could not find a compiled definition. Use --definition to specify one.'
 fi
 
 if [ ! -f "$kompiledDir/syntaxDefinition.kore" ]; then
diff --git a/k-distribution/src/main/scripts/bin/krun b/k-distribution/src/main/scripts/bin/krun
--- a/k-distribution/src/main/scripts/bin/krun
+++ b/k-distribution/src/main/scripts/bin/krun
@@ -113,7 +113,7 @@ $KRUN options:
                            parser. This can be overridden with -p.
       --debugger           Launch the backend in a debugging console.
                            Currently only supported on LLVM backend.
-  -d, --directory DIR      Look for a kompiled directory ending in "-kompiled"
+  -d, --directory DIR      [DEPRECATED] Look for a kompiled directory ending in "-kompiled"
                            under the directory DIR.
       --dry-run            Do not execute backend, but instead print the
                            command that would be executed to stdout.
@@ -228,6 +228,7 @@ do
       ;;
 
       -d|--directory)
+      echo "[Warning]: -d/--directory is deprecated. Use --definition instead." >&2
       dir="$2"
       shift
       ;;
@@ -444,7 +445,7 @@ else
 fi
 
 if ! $hasKompiledDir; then
-  error 1 'Could not find a compiled definition. Use --directory to specify one.'
+  error 1 'Could not find a compiled definition. Use --definition to specify one.'
 fi
 
 # Process configuration variables
@@ -531,7 +532,7 @@ else
   fi
   abs_kompiled_dir=`echo "$(cd "$(dirname "$kompiledDir")"; pwd -P)/$(basename "$kompiledDir")"`
   # llvm-krun creates temp files in the cwd so execute it in $tempDir instead
-  (cd $tempDir; execute llvm-krun $configVars --directory "$abs_kompiled_dir" $llvm_krun_flags --dry-run -nm -o "$(basename $input_file)")
+  (cd $tempDir; execute llvm-krun $configVars --definition "$abs_kompiled_dir" $llvm_krun_flags --dry-run -nm -o "$(basename $input_file)")
 fi
 
 # Expand macros
