k-distribution/{k-util,k*}: factor out error and warning

diff --git a/k-distribution/src/main/scripts/bin/krun b/k-distribution/src/main/scripts/bin/krun
--- a/k-distribution/src/main/scripts/bin/krun
+++ b/k-distribution/src/main/scripts/bin/krun
@@ -28,7 +28,6 @@ llvm_krun_flags=
 configVars=
 dryRun=false
 expandMacros=true
-result=1
 filterSubst=
 fold_lines="fold -s"
 
@@ -66,15 +65,6 @@ if ${verbose}; then
 fi
 
 KRUN=$(basename "$0")
-
-error () {
-  printf "[Error] Critical: $@\n" | $fold_lines 1>&2
-  exit $result
-}
-
-warning () {
-  printf "[Warning] Compiler: $@\n" | $fold_lines 1>&2
-}
 
 print_usage () {
 cat <<HERE
@@ -197,7 +187,7 @@ do
         ;;
 
         *)
-        error 'Invalid value for --color. Should be "on" or "off".'
+        error 1 'Invalid value for --color. Should be "on" or "off".'
         ;;
       esac
       shift
@@ -254,7 +244,7 @@ do
         ;;
 
         *)
-        error 'Invalid value for --io. Should be "on" or "off".'
+        error 1 'Invalid value for --io. Should be "on" or "off".'
         ;;
       esac
       shift
@@ -284,7 +274,7 @@ do
         none) ;;
 
         *)
-        error 'Invalid value for --output. Should be one of "pretty", "program", "kast", "binary", "json", "latex", "kore", or "none".'
+        error 1 'Invalid value for --output. Should be one of "pretty", "program", "kast", "binary", "json", "latex", "kore", or "none".'
         ;;
       esac
       outputMode="$2"
@@ -339,7 +329,7 @@ do
         ;;
 
         *)
-        error 'Invalid value for --smt. Should be "z3" or "none".'
+        error 1 'Invalid value for --smt. Should be "z3" or "none".'
         ;;
       esac
       shift
@@ -408,7 +398,7 @@ if [ -z "${color+unset}" ]; then
 fi
 
 if [[ "${#ARGV[@]}" -gt 1 ]]; then
-  error 'Cannot pass more than one configuration variable as a positional argument.'
+  error 1 'Cannot pass more than one configuration variable as a positional argument.'
 fi
 
 # Compute kompiled directory
@@ -634,8 +624,8 @@ if ! $dryRun; then
 
     output "$outputFile" execute kore-print --directory "$dir" --output "$outputMode" "$kore_output" --color "$colorOpt" $filterSubst
   else
-    error "Backend crashed during rewriting with exit code $result"
+    error ${result} "Backend crashed during rewriting with exit code ${result}"
   fi
 fi
 
-exit $result
+exit ${result}
