use stderr
Former-commit-id: 9f1a763b236ba30ef328140a4d542a67ac6778e6 [formerly d4ecc5ade993919de6b389167d49c54fdde71d03]
Former-commit-id: 437194b44a23a7d9d1f1504d1db761beb3bef094

diff --git a/k-distribution/src/main/scripts/lib/setenv b/k-distribution/src/main/scripts/lib/setenv
--- a/k-distribution/src/main/scripts/lib/setenv
+++ b/k-distribution/src/main/scripts/lib/setenv
@@ -13,7 +13,7 @@ elif [[ `uname` == *MINGW* || `uname` == *MSYS* || `uname` == *CYGWIN* ]]; then
   export PATH="$K_LIB_DIR/native/windows":"$K_LIB_DIR/native/windows$ARCH":"$K_LIB_DIR/native/$ARCH":$PATH
 else
   if [ `uname` != 'Linux' ]; then
-    echo "Warning: unsupported OS detected. Defaulting to Linux mode, but errors may occur."
+    echo "Warning: unsupported OS detected. Defaulting to Linux mode, but errors may occur." 1>&2
   fi
   export PATH="$K_LIB_DIR/native/linux":"$K_LIB_DIR/native/linux$ARCH":$PATH
   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$K_LIB_DIR/native/linux$ARCH"
