Making tests focused to reduce CI bandwidth for investingation of upload-artifact failure

diff --git a/.github/workflows/test-pr.yml b/.github/workflows/test-pr.yml
--- a/.github/workflows/test-pr.yml
+++ b/.github/workflows/test-pr.yml
@@ -30,48 +30,48 @@ jobs:
             git push origin HEAD:${GITHUB_HEAD_REF}
           fi
 
-  nix-maven:
-    name: 'Nix: Maven'
-    runs-on: ubuntu-20.04
-    needs: version-sync
-    steps:
+  # nix-maven:
+  #   name: 'Nix: Maven'
+  #   runs-on: ubuntu-20.04
+  #   needs: version-sync
+  #   steps:
 
-      - name: 'Check out code, set up Git'
-        uses: actions/checkout@v3
-        with:
-          submodules: recursive
-          fetch-depth: 0
-      - run: |
-          git config user.name devops
-          git config user.email devops@runtimeverification.com
+  #     - name: 'Check out code, set up Git'
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: recursive
+  #         fetch-depth: 0
+  #     - run: |
+  #         git config user.name devops
+  #         git config user.email devops@runtimeverification.com
 
-      - name: 'Install Nix'
-        uses: cachix/install-nix-action@v22
-        with:
-          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
-          extra_nix_config: |
-            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
-            substituters = http://cache.nixos.org https://hydra.iohk.io
-            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
+  #     - name: 'Install Nix'
+  #       uses: cachix/install-nix-action@v22
+  #       with:
+  #         install_url: https://releases.nixos.org/nix/nix-2.13.3/install
+  #         extra_nix_config: |
+  #           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
+  #           substituters = http://cache.nixos.org https://hydra.iohk.io
+  #           trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
 
-      - name: 'Install Cachix'
-        uses: cachix/cachix-action@v12
-        with:
-          name: k-framework
-          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
-          skipPush: true
+  #     - name: 'Install Cachix'
+  #       uses: cachix/cachix-action@v12
+  #       with:
+  #         name: k-framework
+  #         authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
+  #         skipPush: true
 
-      - name: 'Update Maven dependencies, push changes'
-        run: |
-          set -x
-          git checkout ${GITHUB_HEAD_REF}
-          if ! git diff --exit-code origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} \
-                -- $(find . -name pom.xml); then
-            nix run .#update-maven
-          fi
-          if git add nix/ && git commit -m 'Update Nix lock files'; then
-            git push
-          fi
+  #     - name: 'Update Maven dependencies, push changes'
+  #       run: |
+  #         set -x
+  #         git checkout ${GITHUB_HEAD_REF}
+  #         if ! git diff --exit-code origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} \
+  #               -- $(find . -name pom.xml); then
+  #           nix run .#update-maven
+  #         fi
+  #         if git add nix/ && git commit -m 'Update Nix lock files'; then
+  #           git push
+  #         fi
 
   test-k:
     name: 'K Tests'
@@ -139,51 +139,51 @@ jobs:
           path: |
             **/*/kore-exec.tar.gz
             
-  compile-nix-flake:
-    name: 'Nix flake'
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - runner: ubuntu-20.04
-            os: ubuntu-20.04
-          - runner: macos-13
-            os: macos-13
-          - runner: MacM1
-            os: self-macos-12
-    runs-on: ${{ matrix.runner }}
-    needs: [nix-maven]
-    steps:
-      - name: 'Check out code'
-        uses: actions/checkout@v3
+  # compile-nix-flake:
+  #   name: 'Nix flake'
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - runner: ubuntu-20.04
+  #           os: ubuntu-20.04
+  #         - runner: macos-13
+  #           os: macos-13
+  #         - runner: MacM1
+  #           os: self-macos-12
+  #   runs-on: ${{ matrix.runner }}
+  #   needs: [nix-maven]
+  #   steps:
+  #     - name: 'Check out code'
+  #       uses: actions/checkout@v3
 
-      - name: 'Upgrade bash'
-        if: ${{ contains(matrix.os, 'macos') }}
-        run: brew install bash
+  #     - name: 'Upgrade bash'
+  #       if: ${{ contains(matrix.os, 'macos') }}
+  #       run: brew install bash
 
-      - name: 'Install Nix'
-        if: ${{ !startsWith(matrix.os, 'self') }}
-        uses: cachix/install-nix-action@v22
-        with:
-          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
-          extra_nix_config: |
-            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
-            substituters = http://cache.nixos.org https://hydra.iohk.io
-            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
+  #     - name: 'Install Nix'
+  #       if: ${{ !startsWith(matrix.os, 'self') }}
+  #       uses: cachix/install-nix-action@v22
+  #       with:
+  #         install_url: https://releases.nixos.org/nix/nix-2.13.3/install
+  #         extra_nix_config: |
+  #           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
+  #           substituters = http://cache.nixos.org https://hydra.iohk.io
+  #           trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
       
-      - name: 'Install Cachix'
-        if: ${{ !startsWith(matrix.os, 'self') }}
-        uses: cachix/cachix-action@v12
-        with:
-          name: k-framework
-          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
+  #     - name: 'Install Cachix'
+  #       if: ${{ !startsWith(matrix.os, 'self') }}
+  #       uses: cachix/cachix-action@v12
+  #       with:
+  #         name: k-framework
+  #         authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
 
-      - name: 'Build K Framework'
-        run: GC_DONT_GC=1 nix build --print-build-logs .
+  #     - name: 'Build K Framework'
+  #       run: GC_DONT_GC=1 nix build --print-build-logs .
 
-      # These tests take a really long time to run on other platforms, so we
-      # skip them unless we're on the M1 runner.
-      - name: 'Test K'
-        if: ${{ matrix.os == 'self-macos-12' }}
-        run: GC_DONT_GC=1 nix build --print-build-logs .#test
+  #     # These tests take a really long time to run on other platforms, so we
+  #     # skip them unless we're on the M1 runner.
+  #     - name: 'Test K'
+  #       if: ${{ matrix.os == 'self-macos-12' }}
+  #       run: GC_DONT_GC=1 nix build --print-build-logs .#test
 
