.github/test-pr: run faster nix-flake-submodules before nix-maven

diff --git a/.github/workflows/test-pr.yml b/.github/workflows/test-pr.yml
--- a/.github/workflows/test-pr.yml
+++ b/.github/workflows/test-pr.yml
@@ -30,54 +30,6 @@ jobs:
             git push origin HEAD:${GITHUB_HEAD_REF}
           fi
 
-  # Update the pinned Maven dependencies for Nix.
-  # This job only runs on push events because we cannot push changes back to a
-  # pull request branch from a fork.
-  nix-maven:
-    name: 'Nix: Maven'
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Check out code'
-        uses: actions/checkout@v2.3.4
-        with:
-          submodules: recursive
-
-      - name: 'Install Nix'
-        uses: cachix/install-nix-action@v14.1
-        with:
-          install_url: "https://releases.nixos.org/nix/nix-2.3.16/install"
-
-      - name: 'Install Cachix'
-        uses: cachix/cachix-action@v10
-        with:
-          name: runtimeverification
-          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
-          skipPush: true
-
-      - name: 'Update Maven dependencies'
-        run: ./nix/update-maven.sh
-
-      - name: 'Commit changes'
-        env:
-          file_pattern: 'nix/'
-        run: |
-          git config user.name rv-devops
-          git config user.email devops@runtimeverification.com
-          if [ -n "$(git status --porcelain $file_pattern)" ]; then
-            if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
-              echo "::error :: The Maven dependencies changed, so the Nix lock files need to be updated. Please run ./nix/update-maven.sh to update the lock files, or move this branch to the runtimeverification/k repository."
-              git diff
-              exit 1
-            elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
-              git add $file_pattern
-              git commit -m 'Update Nix lock files'
-              git push
-            else
-              echo "::error :: Event type not supported: $GITHUB_EVENT_NAME"
-              exit 1
-            fi
-          fi
-
   nix-flake-submodules:
     name: 'Nix flake sumbodule sync'
     runs-on: ubuntu-latest
@@ -141,8 +93,52 @@ jobs:
             fi
           fi
 
+  nix-maven:
+    name: 'Nix: Maven'
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Check out code'
+        uses: actions/checkout@v2.3.4
+        with:
+          submodules: recursive
+
+      - name: 'Install Nix'
+        uses: cachix/install-nix-action@v14.1
+        with:
+          install_url: "https://releases.nixos.org/nix/nix-2.3.16/install"
+
+      - name: 'Install Cachix'
+        uses: cachix/cachix-action@v10
+        with:
+          name: runtimeverification
+          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
+          skipPush: true
+
+      - name: 'Update Maven dependencies'
+        run: ./nix/update-maven.sh
+
+      - name: 'Commit changes'
+        env:
+          file_pattern: 'nix/'
+        run: |
+          git config user.name rv-devops
+          git config user.email devops@runtimeverification.com
+          if [ -n "$(git status --porcelain $file_pattern)" ]; then
+            if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+              echo "::error :: The Maven dependencies changed, so the Nix lock files need to be updated. Please run ./nix/update-maven.sh to update the lock files, or move this branch to the runtimeverification/k repository."
+              git diff
+              exit 1
+            elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
+              git add $file_pattern
+              git commit -m 'Update Nix lock files'
+              git push
+            else
+              echo "::error :: Event type not supported: $GITHUB_EVENT_NAME"
+              exit 1
+            fi
+          fi
+
   test-k:
-    needs: nix-flake-submodules
     name: 'Build and Test K'
     runs-on: [self-hosted, linux]
     steps:
