update.yml: Do not "use" auto-commit action

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -30,7 +30,22 @@ jobs:
         run: ./nix/update-maven.sh
 
       - name: 'Commit changes'
-        uses: stefanzweifel/git-auto-commit-action@v4.7.2
-        with:
-          commit_message: 'Update Maven dependencies'
+        env:
           file_pattern: 'nix/'
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          if [ -n "$(git status --porcelain $file_pattern)" ]; then
+            if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+              echo "::error :: The Maven dependencies changed, so the Nix lock files need to be updated. Please run ./nix/update-maven.sh to update the lock files, or move this branch to the kframework/k repository."
+              git diff
+              exit 1
+            elif [[ $GITHUB_EVENT_NAME == 'push' ]]; then
+              git add $file_pattern
+              git commit -m 'Update Nix lock files'
+              git push
+            else
+              echo "::error :: Event type not supported: $GITHUB_EVENT_NAME"
+              exit 1
+            fi
+          fi
